services:
  postgres:
    image: postgres:latest
    container_name: better-auth-api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: better-auth
      POSTGRES_DB: better-auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
